version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:8080

  dbmysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
    ports:
      - 33006:3306